ALTER TABLE `order`
ADD COLUMN `subtotal` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `shippingFee` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `taxAmount` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `taxPercentage` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `grandTotal` DOUBLE NOT NULL DEFAULT 0;