CREATE TABLE IF NOT EXISTS `coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `value` DOUBLE NOT NULL,
  `minimumOrder` DOUBLE NOT NULL DEFAULT 0,
  `expiryDate` DATETIME(3) NULL,
  `usageLimit` INT NOT NULL DEFAULT 0,
  `usedCount` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `coupon_code_key`(`code`),
  PRIMARY KEY (`id`)
);